### ISSUE TITLE
Create fabric compatibility

### ISSUE THREAD

**Issue by Defetyre** [YUNG-GANG/YUNGs-Better-Fortresses#2]
Will there ever be compatibility with Create for a Fabric version of your mod? It was somewhat surprising that there were none, despite Create being available on Fabric

**Comment by JackiTacki** [comment]
C'mon, Dude.

https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses-fabric

**Comment by yungnickyoung** [comment]
@JackiTacki they're referring to supporting Create on the Fabric version.

@Defetyre Originally we didn't support Create Fabric because we didn't want to have to make each Create piece twice. TL;DR I think I just made a mistake on my end, and it turns out most Create structures on Forge will also work when loaded into Create Fabric. So I'll try to get it added, but no promises.
